### ISSUE TITLE
Published by two authors?

### ISSUE THREAD

**Issue by harrisonhanfei** [openjournals/brief-ideas#88] opened 2015-02-16 07:40 UTC
Dear Editors:

I want to submit a new idea to this Journal. This idea comes from discussions between me and my colleague. So It should be published with our names. But I failed to find the place to put two author names. Is it possible to put two author names?

**Comment by arfon** [comment] 2015-02-16 18:03
Closing as a dupe of https://github.com/openjournals/brief-ideas/issues/67.

**Closed by arfon** 2015-02-16 18:03 UTC
